name:  CI - Main Branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  common:
    uses: vsaitejasgitorg/github-actions-reusable/.github/workflows/ci-main.yaml@main
    with:
      component_name: user
      app_type: nodejs